#include<ostream>
#include<iostream>
#include "../util.h"

int smaller(int a, int b) {
	return a > b ? b :a;
}

int smaller1(int a, int b) {
	return a*(a<b) + b*(b<=a);
}

void upper(char* str, int sz) {
	while (sz > 0) {
		if (str[sz] >= 'a' && str[sz] <= 'z') {
			str[sz] -= 32;
		}
		sz--;
	}
	std::cout << str << "\n";
}

void upper1(char* str, int sz) {
	while (sz > 0) {
		str[sz] = (str[sz]*!(str[sz] >= 'a' && str[sz] <= 'z')) 
			+ (str[sz] - 32)*(str[sz] >= 'a' && str[sz] <= 'z');
		sz--;
	}
	std::cout << str << "\n";
}

void upper2(char* str, int sz) {
	while (sz > 0) {
		str[sz] -= 32*(str[sz] >= 'a' && str[sz] <= 'z');
		sz--;
	}
	std::cout << str << "\n";
}
void upper3(char* str, int sz) {
	while (sz > 0) {
		str[sz] = toupper(str[sz]);
		sz--;
	}
	std::cout << str << "\n";
}
int main() {
	char* str = (char*) malloc(900);
	char* str1 = (char*) malloc(900);
	char* str2 = (char*) malloc(900);
	char* str3 = (char*) malloc(900);
	int sz ;
	sprintf(str, "DSFAfdfaaaaaaaayufsWEREWCxcsdADFSEWCCsdadasdaBRAFAFcadasdadasdaQWQEWQDSDSDazczczcdWEQEQDAdasdasdaWQEDSCZCXZFseaweqeWEWQEDFSfsfsfawQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDdewDADasdasadawdWADADDDDDDDDDqaaaaaaaaaaaaaaaaaaaasfskSFSgdsFSNBGHTaFfsdfEWQv");
	sprintf(str1, "DSFAfdfaaaaaaaayufsWEREWCxcsdADFSEWCCsdadasdaBRAFAFcadasdadasdaQWQEWQDSDSDazczczcdWEQEQDAdasdasdaWQEDSCZCXZFseaweqeWEWQEDFSfsfsfawQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDdewDADasdasadawdWADADDDDDDDDDqaaaaaaaaaaaaaaaaaaaasfskSFSgdsFSNBGHTaFfsdfEWQv");
	sprintf(str2, "DSFAfdfaaaaaaaayufsWEREWCxcsdADFSEWCCsdadasdaBRAFAFcadasdadasdaQWQEWQDSDSDazczczcdWEQEQDAdasdasdaWQEDSCZCXZFseaweqeWEWQEDFSfsfsfawQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDdewDADasdasadawdWADADDDDDDDDDqaaaaaaaaaaaaaaaaaaaasfskSFSgdsFSNBGHTaFfsdfEWQv");
	sprintf(str3, "DSFAfdfaaaaaaaayufsWEREWCxcsdADFSEWCCsdadasdaBRAFAFcadasdadasdaQWQEWQDSDSDazczczcdWEQEQDAdasdasdaWQEDSCZCXZFseaweqeWEWQEDFSfsfsfawQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDdewDADasdasadawdWADADDDDDDDDDqaaaaaaaaaaaaaaaaaaaasfskSFSgdsFSNBGHTaFfsdfEWQv");
	sz = strlen(str);
	TM_INIT
	std::cout <<"rs = " << smaller(10, 9) << "\n";
	std::cout <<"rs1 = " << smaller1(10, 9) << "\n";
	
	TM_START("regular upper")
	upper(str, sz);
	TM_STOP("regular upper");


	TM_START("branchless upper1")
	upper1(str1, sz);
	TM_STOP("branchless upper 1");


	TM_START("branchless upper2")
	upper2(str2, sz);
	TM_STOP("branchless upper 2");

	
	TM_START("branchless upper3-CPP")
	upper3(str3, sz);
	TM_STOP("branchless upper3-CPP");
}
/*i
 * No O
 *  [root@d003100857f0 dod]# ./a.out
 *  rs = 9
 *  rs1 = 9
 *  regular upper ...
 *  DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *  ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *  SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *  regular upper took(0.000103)
 *  branchless upper1 ...
 *  DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *  ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *  SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *  branchless upper 1 took(0.000057)
 *  branchless upper2 ...
 *  DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *  ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *  SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *  branchless upper 2 took(0.000027)
 *  branchless upper3-CPP ...
 *  DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *  ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *  SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *  branchless upper3-CPP took(0.000014)
 *
 *
 *  -O2
 *   [root@d003100857f0 dod]# ./a.out
 *   rs = 9
 *   rs1 = 9
 *   regular upper ...
 *   DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *   ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *   SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *   regular upper took(0.000174)
 *   branchless upper1 ...
 *   DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *   ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *   SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *   branchless upper 1 took(0.000015)
 *   branchless upper2 ...
 *   DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *   ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *   SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *   branchless upper 2 took(0.000009)
 *   branchless upper3-CPP ...
 *   DSFAFDFAAAAAAAAYUFSWEREWCXCSDADFSEWCCSDADASDABRAFAFCADASDADASDAQWQEWQDSDSDAZCZCZCDWEQEQDADASDASDAWQEDSC
 *   ZCXZFSEAWEQEWEWQEDFSFSFSFAWQQEWQQQQQQQQQQQQQQQQQQSFSQQQQQQQQQQQQQQQDDDDDDDDDDDDDSDFFFFFFFFFSDDEWDADASDA
 *   SADAWDWADADDDDDDDDDQAAAAAAAAAAAAAAAAAAAASFSKSFSGDSFSNBGHTAFFSDFEWQV
 *   branchless upper3-CPP took(0.000074)
 *
 *
 * */
